# Generated by Django 3.2.25 on 2026-03-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolibri_kolibri_usb_backup_plugin_plugin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(help_text='Hours before the next backup runs.')),
                ('hour', models.TimeField(blank=True, help_text='Time to run backup if frequency is greater than 24 hours.', null=True)),
                ('day_of_week', models.IntegerField(blank=True, help_text='Day of week to run backup (0-6) if frequency is greater than 168 hours.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BackupStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_successful_backup', models.DateTimeField(blank=True, help_text='Timestamp of the most recent successful backup.', null=True)),
            ],
        ),
    ]
