# Generated by Django 3.2.25 on 2026-03-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolibri_kolibri_usb_backup_plugin_plugin', '0003_add_backup_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupschedule',
            name='frequency',
            field=models.IntegerField(help_text='Seconds between scheduled backups.'),
        ),
    ]
